=== Apress/xml-framemaker/FMXML_part I/samples/simpledoc/sd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--DTD for Book. Typically invoked by
      <!DOCTYPE  Book  SYSTEM
    "C:\Documents and Settings\Kay Ethier\My Documents\APress-FrameMaker71version\samples\simpledoc\sd.dtd">
-->


<!--C:\Documents and Settings\kethier\My
 Documents\Apress-FrameXMLBook\samples\portrait\sdtemplate.fm-->

<!--July 2, 2003-->

<!ELEMENT Book       (TOC?, (LOT | LOF)*, Document, Document+, IX) >

<!ELEMENT Document   (Title?, Section, Section+) >

<!ELEMENT TOC        (#PCDATA) >

<!ELEMENT LOT        (#PCDATA) >

<!ELEMENT LOF        (#PCDATA) >

<!ELEMENT IX         (#PCDATA) >

<!ELEMENT Section    (Head, Body, (Body | Figure | Table | List)*,
                              (Section, Section+)?) >

<!ELEMENT Body       (#PCDATA) >
<!ATTLIST Body       Id        ID        #IMPLIED >

<!ELEMENT Footnote   (#PCDATA) >

<!ELEMENT Head       (#PCDATA) >
<!ATTLIST Head       Id        ID        #IMPLIED >

<!ELEMENT Indented   (#PCDATA) >

<!ELEMENT Index_Marker 
                     EMPTY >
<!ATTLIST Index_Marker 
                     type      CDATA     #IMPLIED
                     text      CDATA     #IMPLIED >

<!ELEMENT Item       (#PCDATA | Indented)* >

<!ELEMENT List       (Item, Item+) >
<!ATTLIST List       Type      (Bullet|Number)  #REQUIRED >

<!ELEMENT Frame      EMPTY >
<!ATTLIST Frame      entity    ENTITY    #IMPLIED
                     file      CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     rasterdpi  NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED
                     impsize   CDATA     #IMPLIED
                     impby     (ref|copy)  #IMPLIED
                     sideways  NMTOKEN   #IMPLIED
                     impang    CDATA     #IMPLIED
                     xoffset   CDATA     #IMPLIED
                     yoffset   CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED >

<!ELEMENT Figure     (Frame, Caption?) >

<!ELEMENT Caption    (#PCDATA) >

<!ELEMENT Table      (TableTitle?, TableHead?, TableBody, TableFoot?) >

<!ELEMENT TableBody  (TableRow+) >

<!ELEMENT TableCell  (#PCDATA) >

<!ELEMENT TableFoot  (TableRow, TableRow*) >

<!ELEMENT TableHead  (TableRow, TableRow*) >

<!ELEMENT TableRow   (TableCell+) >

<!ELEMENT TableTitle (#PCDATA) >
<!ATTLIST TableTitle 
                     Id        ID        #IMPLIED >

<!ELEMENT Title      (Head) >
<!ATTLIST Title      Id        ID        #IMPLIED >

<!ELEMENT Xref       EMPTY >
<!ATTLIST Xref       RefID     IDREF     #REQUIRED
                     format    CDATA     #IMPLIED
                     srcfile   CDATA     #IMPLIED >

<!ELEMENT Emphasis   (#PCDATA) >

<!ELEMENT Equation   EMPTY >
<!ATTLIST Equation   entity    ENTITY    #IMPLIED
                     file      CDATA     #IMPLIED
                     position  NMTOKEN   #IMPLIED
                     align     NMTOKEN   #IMPLIED
                     cropped   NMTOKEN   #IMPLIED
                     float     NMTOKEN   #IMPLIED
                     width     CDATA     #IMPLIED
                     height    CDATA     #IMPLIED
                     angle     CDATA     #IMPLIED
                     bloffset  CDATA     #IMPLIED
                     nsoffset  CDATA     #IMPLIED
                     dpi       NMTOKEN   #IMPLIED
                     alt       CDATA     #IMPLIED >

=== Apress/xml-framemaker/FMXML_part I/samples/simpledoc/xref_idref_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Document SYSTEM "sd.dtd" [

<!-- Begin Document Specific Declarations -->

<?Fm Validation Off?>


<!-- End Document Specific Declarations -->

]>

<?Fm Condition Comment Red SINGLE_UNDERLINE show?>
<Document><Title><Head>A Second Document</Head></Title>
<Section><Head>Introduction</Head>
<Body>This is a brief document created using FrameMaker 7’s portrait
document template.</Body>
<Section><Head>Internal Cross Reference Examples</Head>
<Body>The paragraphs below are for testing internal cross references
for formatting.</Body>
<List Type = "Bullet"><Item><Xref RefID = "BHBDHGDC"
    format = "Heading &#x0026; Page"/></Item>
<Item><Xref RefID = "BHBDHEFF" format = "Heading &#x0026; Page"/></Item>
<Item><Xref RefID = "BHBEHGAC" format = "Heading &#x0026; Page"/></Item></List></Section>
<Section><Head>External Cross Reference Examples</Head>
<Body>The paragraphs below are for testing external cross references
for formatting.</Body>
<List Type = "Bullet"><Item><Xref format = "Heading &#x0026; Page"
    srcfile = "xref_uniqueIDexample.xml#CEGBAFAA"/></Item>
<Item><Xref format = "Heading &#x0026; Page"
    srcfile = "../../../../../../Documents%2520and%2520Settings/Kay%2520Ethier/My%2520Documents/APress-FrameMaker71version/samples/simpledoc/xref_uniqueIDexample.xml#CEGIHGHG"/><Xref
    format = "Heading &#x0026; Page"
    srcfile = "xref_uniqueIDexample.xml#CEGIHGHG"/></Item>
<Item><Xref format = "Heading &#x0026; Page"
    srcfile = "xref_uniqueIDexample.xml#CEGHGHCE"/></Item></List></Section></Section>
<Section><Head>Cross Reference Examples</Head>
<Body Id = "BHBDHGDC">One paragraph to refer to in first doc</Body>
<Body Id = "BHBDHEFF">Second paragraph to refer to in first doc</Body>
<Body Id = "BHBEHGAC">Third paragraph to refer to in first doc</Body></Section></Document>

=== Apress/xml-framemaker/FMXML_part I/samples/simpledoc/simpledoc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Document SYSTEM "sd.dtd" [

<!-- Begin Document Specific Declarations -->


<!-- End Document Specific Declarations -->

]>
<?Fm Condition Comment Red SINGLE_UNDERLINE show?>
<Document><Title><Head>A Small Sample Document</Head></Title>
<Section><Head>Introduction</Head>
<Body>This is a brief document created using FrameMaker 7â€™s portrait
document template. It shows several of the paragraphs in use and
as they might appear to you if you typed them. This text is using a
paragraph format called Body.</Body>
<Section><Head>Bulleted Sample</Head>
<Body>The level 2 heading  is slightly smaller than the heading
above. This is sample text, in a Body paragraph, to show you what
text beneath this heading might look like. A bulleted list follows.</Body>
<List Type = "Bullet"><Item>The first item using the Bulleted paragraph</Item>
<Item>Another item using the Bulleted paragraph</Item>
<Item>The last item using the Bulleted paragraph</Item></List></Section>
<Section><Head>Numbered Sample</Head>
<Body>Repeating from above, the heading level 2  is slightly smaller
than the heading level 1. This is sample text, in a Body paragraph,
to show you what text beneath this heading might look like. A numbred
list is included below.</Body>
<List Type = "Number"><Item>This first paragraph uses Numbered1.</Item>
<Item>This automatically is tagged Numbered.</Item>
<Item>Numbered is repeated on this item.</Item></List></Section></Section>
<Section><Head>Document Limitations</Head>
<Body>This body paragraph is the minimum content required within
this structured section.</Body></Section></Document>

=== Apress/xml-framemaker/FMXML_part I/samples/simpledoc/xref_uniqueIDexample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Document SYSTEM "sd.dtd" [

<!-- Begin Document Specific Declarations -->


<!-- End Document Specific Declarations -->

]>

<?Fm Condition Comment Red SINGLE_UNDERLINE show?>
<Document><Title><Head>A Small Sample Document</Head></Title>
<Section><Head>Introduction</Head>
<Body>This is a brief document created using FrameMaker 7â€™s portrait
document template.</Body>
<Section><Head>Internal Cross Reference Examples</Head>
<Body>The paragraphs below are for testing internal cross references
for formatting.</Body>
<List Type = "Bullet"><Item><Xref RefID = "CEGBAFAA"
    format = "Heading &#x0026; Page"/></Item>
<Item><Xref RefID = "CEGIHGHG" format = "Heading &#x0026; Page"/></Item>
<Item><Xref RefID = "CEGHGHCE" format = "Heading &#x0026; Page"/></Item></List></Section>
<Section><Head>External Cross Reference Examples</Head>
<Body>The paragraphs below are for testing external cross references
for formatting.</Body>
<List Type = "Bullet"><Item><Xref format = "Heading &#x0026; Page"
    srcfile = "xref_idref_example.xml#BHBDHGDC"/></Item>
<Item><Xref format = "Heading &#x0026; Page"
    srcfile = "xref_idref_example.xml#BHBDHEFF"/></Item>
<Item><Xref format = "Heading &#x0026; Page"
    srcfile = "xref_idref_example.xml#BHBEHGAC"/></Item></List></Section></Section>
<Section><Head>Cross Reference Examples</Head>
<Body Id = "CEGBAFAA">Small, single paragraph to refer to in first
doc</Body>
<Body Id = "CEGIHGHG">Smal, second paragraph to refer to in first
doc</Body>
<Body Id = "CEGHGHCE">Small, third paragraph to refer to in first
doc</Body></Section></Document>
